class State:
    MAIN_MENU = 'main_menu'
    AWAITING_CATEGORY_SELECTION = 'awaiting_category_selection'
    AWAITING_WORD = 'awaiting_word'
    AWAITING_TRANSLATION = 'awaiting_translation'
    AWAITING_WORD_TO_DELETE = 'awaiting_word_to_delete'
    TRAINING = 'training'
    VIEWING_PROGRESS = 'viewing_progress'
    WAITING_FOR_EN_WORD = 'waiting_for_en_word'
    WAITING_FOR_RU_WORD = 'waiting_for_ru_word'
    WAITING_FOR_CONFIRMATION = 'waiting_for_confirmation'